import pygame

casillero_uno = pygame.Rect(358, 86, 92, 66)
casillero_dos = pygame.Rect(435,86, 92, 66)
casillero_tres = pygame.Rect(511,86, 92, 66)
casillero_cuatro = pygame.Rect(511,138, 92, 66)
casillero_cinco = pygame.Rect(435,138, 92, 66)
casillero_seis = pygame.Rect(358,138, 92, 66)
casillero_siete = pygame.Rect(280,138, 92, 66)
casillero_ocho = pygame.Rect(202,138, 92, 66)
casillero_nueve = pygame.Rect(202,193, 92, 66)
casillero_diez = pygame.Rect(280,193, 92, 66)
casillero_once = pygame.Rect(358,193, 92, 66)
casillero_doce = pygame.Rect(435,193, 92, 66)
casillero_trece = pygame.Rect(511,193, 92, 66)
casillero_catorce = pygame.Rect(511, 251, 92, 66)
casillero_quince = pygame.Rect(435,251, 92, 66)
casillero_dieciseis = pygame.Rect(358,251, 92, 66)
casillero_diecisiete = pygame.Rect(280,251, 92, 66)
casillero_dieciocho = pygame.Rect(202,251, 92, 66)
casillero_diecinueve = pygame.Rect(202,305, 92, 66)
casillero_veinte = pygame.Rect(280,305, 92, 66)
casillero_veintiuno = pygame.Rect(358,305, 92, 66)
casillero_veintidos = pygame.Rect(435,305, 92, 66)
casillero_veintitres = pygame.Rect(511,305, 92, 66)
casillero_veinticuatro = pygame.Rect(511,362, 92, 66)
casillero_veinticinco = pygame.Rect(435,362, 92, 66)
casillero_veintiseis = pygame.Rect(358,362, 92, 66)
casillero_veintisiete = pygame.Rect(280,362, 92, 66)
casillero_veintiocho = pygame.Rect(202,362, 92, 66)
casillero_veintinueve = pygame.Rect(202,421, 92, 66)
casillero_treinta = pygame.Rect(280, 421, 92, 66)
casillero_meta = pygame.Rect(358,421, 92, 66)


#         pygame.draw.rect(pantalla, naranja, casillero_1)
#         pygame.draw.rect(pantalla,naranja, casillero_2)
#         pygame.draw.rect(pantalla,naranja, casillero_tres)
#         pygame.draw.rect(pantalla,naranja, casillero_cuatro)
#         pygame.draw.rect(pantalla,naranja, casillero_cinco)
#         pygame.draw.rect(pantalla,naranja, casillero_seis)
#         pygame.draw.rect(pantalla,naranja, casillero_siete)
#         pygame.draw.rect(pantalla,naranja, casillero_ocho)
#         pygame.draw.rect(pantalla,naranja, casillero_nueve)
#         pygame.draw.rect(pantalla,naranja, casillero_diez)
#         pygame.draw.rect(pantalla,naranja, casillero_once)
#         pygame.draw.rect(pantalla,naranja, casillero_doce)
#         pygame.draw.rect(pantalla,naranja, casillero_trece)
#         pygame.draw.rect(pantalla,naranja, casillero_catorce)
#         pygame.draw.rect(pantalla,naranja, casillero_quince)
#         pygame.draw.rect(pantalla,naranja, casillero_16)
#         pygame.draw.rect(pantalla,naranja, casillero_17)
#         pygame.draw.rect(pantalla,naranja, casillero_18)
#         pygame.draw.rect(pantalla,naranja, casillero_19)
#         pygame.draw.rect(pantalla,naranja, casillero_20)
#         pygame.draw.rect(pantalla,naranja, casillero_21)
#         pygame.draw.rect(pantalla,naranja, casillero_22)
#         pygame.draw.rect(pantalla,naranja, casillero_23)
#         pygame.draw.rect(pantalla,naranja, casillero_24)
#         pygame.draw.rect(pantalla,naranja, casillero_25)
#         pygame.draw.rect(pantalla,naranja, casillero_26)
#         pygame.draw.rect(pantalla,naranja, casillero_27)
#         pygame.draw.rect(pantalla,naranja, casillero_28)
#         pygame.draw.rect(pantalla,naranja, casillero_29)
#         pygame.draw.rect(pantalla,naranja, casillero_30)
#         pygame.draw.rect(pantalla,naranja, casillero_meta)